### ISSUE TITLE
Add Clear Search Option to clear search

### ISSUE THREAD

**Issue by AmanR28** [creativecommons/ccsearch-browser-extension#120]
**Is your feature request related to a problem? Please describe.**
As the search is getting stored, so the user might want to clear stored search, instead of disabling the whole feature.

**Describe the solution you'd like**
Add a clear search icon to clear the search

**Additional context**
PS:: I want to work on it.

@makkoncept  Please Review

**Comment by makkoncept** [comment]
@AmanR28 Looks like a good idea! This was actually the main reason why the option to toggle off the search in localstorage is needed, because some users might want to start a fresh session when they open the extension. 
An icon that would clear the search, both from the UI and the localStorage, would be a good addition. 

I suppose we need to merge #119 before you can work on this (?). A lot is happening in that PR. I would test and review it soon.

**Comment by AmanR28** [comment]
> I suppose we need to merge #119 before you can work on this (?). A lot is happening in that PR. I would test and review it soon.

They might be independent.

**Comment by makkoncept** [comment]
Okay :+1:
