### ISSUE TITLE
Adding a button to get embed code

### ISSUE THREAD

**Issue by Blackcipher101** [creativecommons/ccsearch-browser-extension#125]
**Is your feature request related to a problem? **
I didn't get it that if you click the photo you get embed code there is no way to make it out

**Describe the solution you'd like**
A small button which appears when you hover over the image  
which looks like ``<\>``
**Additional context**
![Screenshot from 2020-02-04 18-28-40](https://user-images.githubusercontent.com/33775493/73746864-36da1480-477c-11ea-8cbe-5c8a876ce18f.png)

**Comment by makkoncept** [comment]
@Blackcipher101 By `embed code`, do you mean an HTML image tag with the image as the source or the license attribution of the image?

**Comment by Blackcipher101** [comment]
Yes

**Comment by makkoncept** [comment]
@Blackcipher101 license attribution?

**Comment by Blackcipher101** [comment]
The html tag code

**Comment by Blackcipher101** [comment]
I can think I can solve it I will start working on it

**Comment by makkoncept** [comment]
@Blackcipher101 I think this feature is not needed in the extension. The space available on the image thumbnails is already cluttered(with name, provider icon, license icons and bookmark icon) and only the absolutely necessary icons are to be placed there. I don't think this icon is necessary because:
- The user-base of the extension is very diverse (teachers, blog writers, scientists etc). The workflow most them follow: search for image -> click on the image they want -> download the image and copy the attribution from the info popup -> use the image in a blog post or a PPT with valid attribution. They might not find this feature very useful.
- One of the most important aspect of CC Licenses are attribution. I think addition of this feature will make more users skip copying attribution from the info popup.
