### ISSUE TITLE
Upgrade CC Catalog API usage to v1

### ISSUE THREAD

**Issue by kgodey** [creativecommons/ccsearch-browser-extension#144]
@makkoncept, I'm assigning to you to flesh this out further and make this issue ready for contribution. Let me know if you have questions.

**Comment by makkoncept** [comment]
Related Issues:
- [ ] #146 
- [ ] #147 
- [ ] #148 
- [ ] #149 

More will be added as I complete digging through the code.

**Comment by makkoncept** [comment]
The core functions and workflow have been upgraded to the API v1.0. An update has been pushed for review on the browser extension stores with some important bug fixes ([changelog](https://github.com/creativecommons/ccsearch-browser-extension/releases/tag/v1.2.8)).

**Comment by makkoncept** [comment]
With the search syntax guide update in the options page, the migration to CC Catalog API v1 is complete :)

 A new version has been pushed to the browser stores. The review might take more time than usual due to the Covid-19 outbreak (atleast for the chrome store. They notified about this in a mail).
