### ISSUE TITLE
Formatting exported bookmark json file

### ISSUE THREAD

**Issue by darkshredder** [creativecommons/ccsearch-browser-extension#318]
**Is your feature request related to a problem? Please describe.**
Currently the json file downloaded is not properly formatted or indented

**Describe the solution you'd like**
I would like to format and indent json file downloaded 

**Additional context**
![Screenshot from 2020-12-16 21-35-58](https://user-images.githubusercontent.com/52625656/102373911-b6648100-3fe6-11eb-87f7-02af3c94684f.png)
This is how the output will be finally
If this is approved I would like to implement this feature

**Comment by makkoncept** [comment]
@darkshredder Thanks for the feature request but I think that this is not required in the extension. The reason is that the exported bookmark files are not meant for raw consumption by the users. They are imported through the options page and then the user opens the bookmarks section in the extension popup to view them. These bookmark files can be used for archiving bookmarks or sharing bookmarks to another  user and therefore having a small size is ideal. These extra white-spaces will only increase the size. The benefit of aesthetics is not what we are looking for here.
