### ISSUE TITLE
Dark mode toggle from popup is not persistent

### ISSUE THREAD

**Issue by ritesh-pandey** [creativecommons/ccsearch-browser-extension#45]
**Is your feature request related to a problem? Please describe.**
Dark mode toggle from popup is not persistent. When we re-open the popup, previously toggled mode is not honored.

**Describe the solution you'd like**
Color toggle should be synced to database so that old state can be retrieved.

**Describe alternatives you've considered**
Set required mode in Options section.

**Additional context**
Code https://github.com/creativecommons/ccsearch-browser-extension/blob/master/src/popup/popup.js#L323

**Comment by makkoncept** [comment]
Hi @ritesh-pandey. So I think this boils down to the user's own experience and expectations from the UI.  I had no issues with having to open the options page to set the default dark mode preference in the extension because generally, before using any application, I change the UI settings of it to suit my needs. 
But, the fact that you expected the dark mode state to persist from the popup itself means that other users might think this way too. Also, it feels more intuitive.

We should implement this. Also, there is no need for having the tab for dark mode on the options page anymore. 
Let me know if you want to work on this!

**Comment by sharmaaditya570191** [comment]
Hi @makkoncept I would like to take this up. Could you please suggest how to implement this?

**Comment by makkoncept** [comment]
Fixed in 0891da7b1ace0b9abb8d664b899f7468ffe4370d, 1ad2740fef1015db30e1a14d55a64aac4e33269c and 75dee6857f00b87eb60e7a0dff9718d82f416c29
