### ISSUE TITLE
Add Internet Archive as a source

### ISSUE THREAD

**Issue by stragu** [creativecommons/ccsearch-browser-extension#64]
It would be great to have access to Internet Archive search results. I know that CC licences are available on there.

https://archive.org/

This integration could be limited to images only using `mediatype:"image"`

https://archive.org/details/image?and[]=mediatype%3A%22image%22

There are close to 3.5 million images available.

To filter by licence, the CC abbreviations can be used. For example:

https://archive.org/details/image?and[]=mediatype%3A%22image%22&and[]=licenseurl:http*by-nc*

...gives more than 110,000 results.

There is more information about licence search here:

https://help.archive.org/hc/en-us/articles/360018359991-Search-A-Basic-Guide

**Comment by makkoncept** [comment]
Hi @stragu, thanks for the suggestion.
There are no plans for adding an API other than [CC Catalog](https://github.com/creativecommons/cccatalog-api/) because then we will face issues like managing two different API results, not having the required image information and not having the same filter endpoints. 
I have brought this issue to the attention of the CC engineering team. Other image sources will be integrated with CC Catalog API in the future and hence be made available in the extension also.

**Comment by kgodey** [comment]
@stragu I recommend opening a similar issue on https://github.com/creativecommons/cccatalog

**Comment by stragu** [comment]
That makes absolute sense, thank you for the explanation and pointing me to the right spot, @makkoncept and @kgodey !

All the best.
