### ISSUE TITLE
Search should retain even after closing popup

### ISSUE THREAD

**Issue by AmanR28** [creativecommons/ccsearch-browser-extension#79]
**Is your feature request related to a problem? Please describe.**
The search disappears if we close the popup.

**Describe the solution you'd like**
The search should be accessible for that session until changed by user.

**Additional context**
I would like to work on this.

**Comment by makkoncept** [comment]
@AmanR28 We tried this during the early development stage. The one problem that occurred was the increased start-up time of the extension. But, since the code has been improved significantly, it might work now.
The obvious solution is to store the search query in the localStorage to persist it across sessions.

Also, not all users might want to have this feature, therefore we can add a tab in the Options page with the title "Other Settings". There we can add a setting to toggle off this feature if the user wants. 
I will make a separate issue for this. Just make sure that your implementation takes into account this aspect also.

**Comment by AmanR28** [comment]
@makkoncept Please create an issue for user choice for storing search, or can I?

PS: Assign it to me, please.

**Comment by makkoncept** [comment]
@AmanR28 Let me create the issue.

**Comment by AmanR28** [comment]
I will post a PR on this soon.
